from __future__ import annotations
from enum import Enum
from typing import Any, Optional
from pydantic import BaseModel, Field


class ContextStrategy(str, Enum):
    DIRECT_CONTEXT = "DIRECT_CONTEXT"
    RAG = "RAG"
    ITERATIVE_RAG = "ITERATIVE_RAG"
    HIERARCHICAL_RETRIEVAL = "HIERARCHICAL_RETRIEVAL"
    MAP_REDUCE = "MAP_REDUCE"
    MULTI_AGENT_RESEARCH = "MULTI_AGENT_RESEARCH"
    TOOL_COMPUTATION = "TOOL_COMPUTATION"
    HYBRID = "HYBRID"


class ContextSufficiencyStatus(str, Enum):
    SUFFICIENT = "SUFFICIENT"
    INSUFFICIENT = "INSUFFICIENT"
    CONFLICTED = "CONFLICTED"
    UNCERTAIN = "UNCERTAIN"


class ContradictionType(str, Enum):
    TRUE_CONTRADICTION = "TRUE_CONTRADICTION"
    VERSION_DIFFERENCE = "VERSION_DIFFERENCE"
    TEMPORAL_DIFFERENCE = "TEMPORAL_DIFFERENCE"
    SCOPE_DIFFERENCE = "SCOPE_DIFFERENCE"
    CONDITION_DIFFERENCE = "CONDITION_DIFFERENCE"
    UNRESOLVED = "UNRESOLVED"


class ProgressiveLevel(int, Enum):
    METADATA = 0
    SUMMARY = 1
    EXCERPT = 2
    SECTION = 3
    FULL_DOC = 4


class ContextSlotType(str, Enum):
    SYSTEM_POLICY = "SYSTEM_POLICY"
    CURRENT_GOAL = "CURRENT_GOAL"
    CONSTRAINTS = "CONSTRAINTS"
    KNOWN_FACTS = "KNOWN_FACTS"
    PRIMARY_EVIDENCE = "PRIMARY_EVIDENCE"
    SECONDARY_EVIDENCE = "SECONDARY_EVIDENCE"
    CONTRADICTIONS = "CONTRADICTIONS"
    TOOL_RESULTS = "TOOL_RESULTS"
    MEMORY = "MEMORY"
    WORKSPACE = "WORKSPACE"
    OUTPUT_RESERVE = "OUTPUT_RESERVE"


class OrderingStrategy(str, Enum):
    RELEVANCE_FIRST = "RELEVANCE_FIRST"
    EVIDENCE_FIRST = "EVIDENCE_FIRST"
    CLAIM_EVIDENCE = "CLAIM_EVIDENCE"
    SUMMARY_THEN_DETAIL = "SUMMARY_THEN_DETAIL"
    POSITION_AWARE = "POSITION_AWARE"
